<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="LAPTOP-2NO4TO14" failures="0" tests="1" name="com.bdd.runnerTest.RunnerTest" time="249.839" errors="1" timestamp="04 Jul 2021 23:14:54 GMT" skipped="0">
  <testcase classname="com.bdd.runnerTest.RunnerTest" name="feature" time="249.839">
    <error message="java.lang.AssertionError: Error al intentar obtener elemento. Key: xpath - Locator: /html/body/modal-container/div/div/ng-component/div/h3" type="cucumber.runtime.CucumberException">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: Error al intentar obtener elemento. Key: xpath - Locator: /html/body/modal-container/div/div/ng-component/div/h3
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.AssertionError: Error al intentar obtener elemento. Key: xpath - Locator: /html/body/modal-container/div/div/ng-component/div/h3
	at org.testng.Assert.fail(Assert.java:94)
	at com.bdd.VISOR.BaseClass.getElement(BaseClass.java:139)
	at com.bdd.VISOR.modoVisor.page.AveriasPage.validarMensajeUsuario(AveriasPage.java:96)
	at com.bdd.VISOR.modoVisor.step.AveriasStep.validarMensajeUsuario(AveriasStep.java:47)
	at com.bdd.VISOR.modoVisor.stepdefinition.AveriasStepDefinition.seEsperaElMensajeConElTestRealizado(AveriasStepDefinition.java:46)
	at âœ½.Then Se espera el mensaje "Servicio no disponible" con el test realizado(visor/diagnosticoReset.feature:61)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- com.bdd.runnerTest.RunnerTest -->
